services:
  - type: web
    name: portfolio-saas-api
    env: node
    rootDir: server
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: *,https://your-frontend.vercel.app,https://your-frontend.netlify.app
      - key: MONGODB_URI
        value: mongodb+srv://kunalmangla447_db_user:A1DyHT53zxNiBRtA@cluster0.mongodb.net/portfolio?retryWrites=true&w=majority
